// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhfahwoacuuiafutybic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oZmFod29hY3V1aWFmdXR5YmljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjU5NzEsImV4cCI6MjA2NDQ0MTk3MX0.L2Q3GbYrfhta48cN4kwG9KyR1t-NrzTDRx1vxyEPofU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);